modLoader="javafml"
loaderVersion="[1,)"
license="All Rights Reserved"

[[mods]]
modId="taroflavoured"
version="0.1.0-1.21.1"
displayName="Taro Flavoured"
authors="Taro Flavoured"
description='''A NeoForge 1.21.1 mod implementing the selected Taro Flavoured feature set.'''

[[mixins]]
config="taroflavoured.mixins.json"

[[dependencies.taroflavoured]]
modId="neoforge"
type="required"
versionRange="[21.1.235,)"
ordering="NONE"
side="BOTH"

[[dependencies.taroflavoured]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="NONE"
side="BOTH"
