modLoader="javafml"
loaderVersion="[1,)"
license="All Rights Reserved"

[[mods]]
modId="matchainfused"
version="0.1.0-1.21.1"
displayName="Matcha Infused"
authors="Violeterra / Matcha Flavoured"
description='''A NeoForge 1.21.1 recreation of the Matcha Infused feature subset.'''

[[dependencies.matchainfused]]
modId="neoforge"
type="required"
versionRange="[21.1.235,)"
ordering="NONE"
side="BOTH"

[[dependencies.matchainfused]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="NONE"
side="BOTH"
