modLoader="javafml"
loaderVersion="[1,)"
license="All Rights Reserved"

[[mods]]
modId="taroflavoured"
version="0.1.0-1.21.1"
displayName="Taro Flavoured"
authors="Taro Flavoured"
description='''A NeoForge 1.21.1 mod implementing the selected Taro Flavoured feature set.'''
enumExtensions="META-INF/enumextensions.json"

[[dependencies.taroflavoured]]
modId="neoforge"
type="required"
versionRange="[21.1.235,)"
ordering="NONE"
side="BOTH"

[[dependencies.taroflavoured]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="NONE"
side="BOTH"

[[dependencies.taroflavoured]]
modId="mounts_of_mayhem"
type="required"
versionRange="[2.1.0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.taroflavoured]]
modId="create"
type="required"
versionRange="[6.0.10,)"
ordering="AFTER"
side="BOTH"

[[dependencies.taroflavoured]]
modId="mr_magic_mirrors"
type="required"
versionRange="[1.0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.taroflavoured]]
modId="copperagebackport"
type="required"
versionRange="[0.1.4,)"
ordering="AFTER"
side="BOTH"
